[tool.poetry]
name = "llama-index-playground"
version = "0.1.0"
description = ""
authors = ["vikyw89 <vikyw89@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
llama-index = "^0.9.20"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
